# Generated by Django 4.1.4 on 2023-06-25 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionContra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_seccion', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=50)),
                ('contraseña', models.IntegerField()),
                ('action', models.CharField(max_length=80, null=True)),
                ('detail', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contrasena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contra', models.CharField(max_length=20, unique=True)),
                ('link', models.CharField(max_length=265)),
                ('usuario', models.CharField(max_length=60)),
                ('contraseña', models.CharField(max_length=60)),
                ('info', models.CharField(max_length=260)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passbase.seccioncontra')),
            ],
        ),
    ]
