# Generated by Django 4.1.4 on 2023-10-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passbase', '0002_alter_contrasena_nombre_contra'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrasena',
            name='actualizacion',
            field=models.IntegerField(default=30),
        ),
    ]
