# Generated by Django 4.1.4 on 2023-11-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passbase', '0004_logdata_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdata',
            name='detail',
            field=models.CharField(max_length=1000),
        ),
    ]
