# Generated by Django 4.1.4 on 2023-12-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passbase', '0005_alter_logdata_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrasena',
            name='actualizacion',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
