# Generated by Django 4.1.4 on 2024-06-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passbase', '0007_contrasena_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrasena',
            name='is_personal',
            field=models.BooleanField(default=False),
        ),
    ]
