# Generated by Django 4.1.4 on 2024-07-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passbase', '0009_contrasena_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrasena',
            name='contraseña',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contrasena',
            name='nombre_contra',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='contrasena',
            name='usuario',
            field=models.CharField(max_length=255),
        ),
    ]
