# Generated by Django 4.1.4 on 2024-07-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passbase', '0010_alter_contrasena_contraseña_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdata',
            name='detail',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
