# Generated by Django 4.1.4 on 2024-07-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passbase', '0012_alter_contrasena_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrasena',
            name='contraseña',
            field=models.CharField(max_length=500),
        ),
    ]
