# Generated by Django 4.1.4 on 2024-07-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passbase', '0013_alter_contrasena_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdata',
            name='password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
