# Generated by Django 4.1.4 on 2024-09-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passbase', '0014_alter_logdata_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrasena',
            options={'verbose_name': 'Contraseña', 'verbose_name_plural': 'Contraseñas'},
        ),
        migrations.AlterModelOptions(
            name='logdata',
            options={'verbose_name': 'Log'},
        ),
        migrations.AlterModelOptions(
            name='seccioncontra',
            options={'verbose_name': 'Seccion', 'verbose_name_plural': 'Secciones'},
        ),
        migrations.AlterField(
            model_name='logdata',
            name='action',
            field=models.CharField(blank=True, default='vacio', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logdata',
            name='password',
            field=models.CharField(blank=True, default='vacio', max_length=500),
            preserve_default=False,
        ),
    ]
