# Generated by Django 4.1.4 on 2024-09-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passbase', '0015_alter_contrasena_options_alter_logdata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrasena',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
