# Generated by Django 4.1.4 on 2023-07-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrapermission',
            name='perm_active',
            field=models.BooleanField(default=True),
        ),
    ]
