# Generated by Django 4.1.4 on 2024-06-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passbase', '0009_contrasena_owner'),
        ('permission', '0002_contrapermission_perm_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_name', models.CharField(max_length=60)),
                ('contrasenas', models.ManyToManyField(related_name='roles', to='passbase.contrasena')),
            ],
        ),
    ]
