# Generated by Django 4.1.4 on 2024-06-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0004_userroles'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionroles',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userroles',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
