# Generated by Django 4.1.4 on 2024-06-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0005_permissionroles_created_userroles_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionroles',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
