# Generated by Django 4.1.4 on 2024-06-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0006_permissionroles_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionroles',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
