# Generated by Django 4.1.4 on 2023-10-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='permiso_contra',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='static/', width_field=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
