# Generated by Django 4.2.6 on 2024-07-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_customuser_address_customuser_admission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='departure_motive',
            field=models.CharField(max_length=1000, null=True, verbose_name='Motivo de baja'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Egreso'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(max_length=80, null=True, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Nro Telefono'),
        ),
    ]
