# Generated by Django 4.2.6 on 2024-07-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_customuser_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='menu_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Color de menu'),
        ),
    ]
