# Generated by Django 4.1.4 on 2024-07-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_customuser_menu_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='menu_color',
            field=models.CharField(blank=True, default='#212629', max_length=7, null=True, verbose_name='Color de menu'),
        ),
    ]
