# Generated by Django 4.2.6 on 2024-07-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_customuser_menu_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='departure_motive',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Motivo de baja'),
        ),
    ]
