# Generated by Django 4.1.4 on 2024-08-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_customuser_departure_motive'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_role',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rol asignado'),
        ),
    ]
