# Generated by Django 4.1.4 on 2024-09-10 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0008_alter_contrapermission_options_and_more'),
        ('login', '0012_alter_customuser_assigned_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='assigned_role',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='permission.permissionroles', verbose_name='Rol asignado'),
        ),
    ]
