# threat_intel/services/report_generator.py
"""Utilidades para generar archivos binarios (PDF/Markdown/JSON) desde reportes."""
from __future__ import annotations
from typing import Optional, Tuple
from datetime import datetime


def generate_report_pdf(report) -> Tuple[str, bytes]:
    """Genera un PDF a partir del HTML del reporte para adjuntar."""
    try:
        from weasyprint import HTML
        from io import BytesIO
    except ImportError:
        raise ImportError(
            "WeasyPrint not installed. Install with: pip install weasyprint"
        )
    
    if not report.body_html:
        raise ValueError("Report must have body_html content to generate PDF")
    
    # Prepare HTML with minimal styling for PDF
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; margin: 20px; }}
            h1, h2, h3 {{ color: #333; }}
            .header {{ border-bottom: 2px solid #667eea; padding-bottom: 10px; margin-bottom: 20px; }}
            .footer {{ margin-top: 30px; padding-top: 10px; border-top: 1px solid #ddd; font-size: 12px; color: #666; }}
            table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
            th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
            th {{ background-color: #f5f5f5; }}
            code {{ background-color: #f4f4f4; padding: 2px 6px; border-radius: 3px; }}
            pre {{ background-color: #f4f4f4; padding: 10px; overflow-x: auto; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>{report.subject}</h1>
            <p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </div>
        {report.body_html}
        <div class="footer">
            <p>This report was automatically generated by Threat Intelligence System</p>
        </div>
    </body>
    </html>
    """
    
    # Generate PDF
    pdf_buffer = BytesIO()
    HTML(string=html_content).write_pdf(pdf_buffer)
    pdf_bytes = pdf_buffer.getvalue()
    
    # Generate filename with timestamp
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"threat_report_{report.id}_{timestamp}.pdf"
    
    return filename, pdf_bytes


def generate_report_markdown(report) -> Tuple[str, bytes]:
    """Exporta el reporte como archivo Markdown."""
    content = f"""# {report.subject}

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

{report.body_md}

---

*Generated by Threat Intelligence System*
"""
    
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"threat_report_{report.id}_{timestamp}.md"
    
    return filename, content.encode('utf-8')


def generate_report_json(report) -> Tuple[str, bytes]:
    """Exporta el reporte en formato JSON para consumo automatizado."""
    import json
    
    data = {
        "id": report.id,
        "subject": report.subject,
        "body_markdown": report.body_md,
        "body_html": report.body_html,
        "recipients": report.recipients or [],
        "generated_at": datetime.now().isoformat(),
        "run_id": getattr(report.run, 'id', None) if hasattr(report, 'run') else None,
    }
    
    json_content = json.dumps(data, indent=2, ensure_ascii=False).encode('utf-8')
    
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"threat_report_{report.id}_{timestamp}.json"
    
    return filename, json_content
