# Generated by Django 4.1.4 on 2024-05-12 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passbase', '0007_contrasena_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=60)),
                ('viewed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('id_contrasena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passbase.contrasena')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(max_length=50)),
                ('type_user', models.IntegerField(choices=[(0, 'Staff'), (1, 'Admin')], default=1)),
                ('action', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=60)),
                ('viewed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('id_contrasena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passbase.contrasena')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
