# Generated by Django 4.1.4 on 2024-05-12 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_usernotifications_id_user_share_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminnotification',
            options={'verbose_name': 'Notificaciones a admin'},
        ),
        migrations.AlterModelOptions(
            name='usernotifications',
            options={'verbose_name': 'Notificaciones a usuario'},
        ),
        migrations.RemoveField(
            model_name='usernotifications',
            name='id_user_share',
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='id_user_share',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='id_user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
