# Generated by Django 4.2.6 on 2024-05-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_adminnotification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotifications',
            name='comment',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='type_notification',
            field=models.CharField(max_length=150),
        ),
    ]
